# Generated by Django 5.0.6 on 2024-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(default=None, null=True),
        ),
    ]
