# Generated by Django 5.0.6 on 2024-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('boating_repair', 'Boating Repair'), ('motorcycle_repair', 'Motorcycle Repair'), ('software_development', 'Software Development'), ('investing', 'Investing'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
