# Generated by Django 5.0.6 on 2024-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_workreference_category_alter_aboutsection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreference',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='category',
            field=models.CharField(blank=True, choices=[('experience', 'Experience'), ('education', 'Education'), ('technical', 'Technical Strengths'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
