# Generated by Django 5.0.6 on 2024-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_workreference_date_alter_workreference_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreference',
            name='date',
        ),
        migrations.AddField(
            model_name='workreference',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workreference',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
