# Generated by Django 5.0.6 on 2024-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_workreference_date_workreference_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreference',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='file',
            field=models.FileField(blank=True, upload_to='references/'),
        ),
    ]
