# Generated by Django 5.0.6 on 2024-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_workreference_job_title_alter_workreference_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreference',
            name='job_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
