# Generated by Django 5.0.6 on 2024-05-23 18:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreference',
            name='category',
            field=models.CharField(choices=[('experience', 'Experience'), ('education', 'Education'), ('technical', 'Technical Strengths'), ('other', 'Other')], default='experience', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
    ]
