# Generated by Django 5.0.6 on 2024-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_workreference_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreference',
            name='file',
            field=models.FileField(blank=True, upload_to='cv/attachments/'),
        ),
    ]
