# Generated by Django 5.0.6 on 2024-07-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0002_boatlisting_created_at_boatlisting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boat_pictures/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('boat_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='boating.boatlisting')),
            ],
        ),
    ]
