# Generated by Django 5.0.6 on 2024-07-07 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='boating/thumbnails'),
            preserve_default=False,
        ),
    ]
