# Generated by Django 5.0.6 on 2024-07-07 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0004_boatlisting_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatlisting',
            name='price',
            field=models.PositiveIntegerField(default=70000),
            preserve_default=False,
        ),
    ]
