# Generated by Django 5.0.6 on 2024-07-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0005_alter_boatlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='year',
            field=models.PositiveIntegerField(default=1989),
            preserve_default=False,
        ),
    ]
