# Generated by Django 5.0.6 on 2024-07-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0006_boatlisting_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='top_speed',
            field=models.PositiveIntegerField(default=32),
            preserve_default=False,
        ),
    ]
