# Generated by Django 5.0.6 on 2024-07-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0007_boatlisting_top_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatlisting',
            name='engine',
        ),
        migrations.AddField(
            model_name='engine',
            name='boat_listing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='boating.boatlisting'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('boat_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='boating.boatlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('boat_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='boating.boatlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('boat_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='boating.boatlisting')),
            ],
        ),
    ]
