# Generated by Django 5.0.6 on 2024-07-11 12:01

import autoslug.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0008_remove_boatlisting_engine_engine_boat_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatlisting',
            name='beam',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='boat_type',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='length',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='top_speed',
        ),
        migrations.RemoveField(
            model_name='boatlisting',
            name='year',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='value',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='value',
        ),
        migrations.AddField(
            model_name='construction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='beam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='boat_type',
            field=models.CharField(choices=[('motorboat', 'Motorboat'), ('sailboat', 'Sailboat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='overview',
            name='top_speed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overview',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
