# Generated by Django 5.0.6 on 2024-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0009_remove_boatlisting_beam_remove_boatlisting_boat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='title',
        ),
        migrations.AddField(
            model_name='boatlisting',
            name='title',
            field=models.CharField(default='Sea Ray', max_length=80),
            preserve_default=False,
        ),
    ]
