# Generated by Django 5.0.6 on 2024-07-11 12:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boating', '0010_remove_overview_title_boatlisting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='slug',
        ),
        migrations.AddField(
            model_name='boatlisting',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
    ]
