# Generated by Django 5.0.6 on 2024-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
