# Generated by Django 5.0.6 on 2024-06-13 09:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='references',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='References'),
        ),
    ]
