# Generated by Django 5.0.6 on 2024-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('se', 'Swedish'), ('en', 'English')], default='se', max_length=20),
        ),
    ]
