# Generated by Django 5.0.6 on 2024-07-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_published'),
        ('articles', '0013_alter_article_thumbnail'),
    ]

    operations = [
    ]
