# Generated by Django 5.0.6 on 2024-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
