# Generated by Django 5.0.6 on 2024-05-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contentsnippet_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsnippet',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
